android/build.gradle
How to consume in a target app:
CMakeList.txt:
```
find_package(react-native-worklets REQUIRED CONFIG)
target_link_libraries(
${PACKAGE_NAME}
react-native-worklets::rnworklets
```
How to include header:
```c++
#include <rnworklets/JsiBaseDecorator.h>
#include <rnworklets/JsiWorkletContext.h>
```
**It needs to be tested on a fresh app!!**
=> add prefab support

android/CMakeLists.txt
Fixes "`<folly/folly-config.h> not found`" error
=> fix: Add Folly flags from RN core to buildscript

android/src/main/java/com/worklets/WorkletsModule.java
If this isn't blocking & synchronous, it runs on a background Thread. It is not safe to access the JSI Runtime on the background Thread, so this crashes with a SIG_ABRT otherwise
=> fix: Make `install` blocking & synchronous to run on JS Thread

cpp/JsiWorklet.h, cpp/JsiWorkletApi.cpp, cpp/JsiWorkletContext.cpp, cpp/JsiWorkletContext.h, cpp/decorators/JsiPerformanceDecorator.h, cpp/decorators/JsiSetImmediateDecorator.h, cpp/wrappers/JsiPromiseWrapper.cpp
Api now takes runtime as parameter and maps runtime with context instead of mapping on thread id.
=> Changed getCurrent api to map context on runtime pointer instead of thread id.

cpp/JsiWorkletContext.cpp
We need to call getWorkletRuntime() to ensure that the runtime as been created. Without this we just added a random pointer value to the map - this PR fixes this.
=> Fixed wrong emplace in mapping emplace

src/plugin/__tests__/__snapshots__/index.spec.js.snap, src/plugin/__tests__/index.spec.js, src/plugin/index.js
To avoid the problem with nested worklets loosing its code in the outer worklet's code definition, we changed the order of processing from using enter to exit in the plugin.
Added test and fixed plugin.
=> fix: Updated support for nested plugins

cpp/JsiWorkletContext.cpp
The JNI ThreadScope is required to call into JNI on Android.
I'm not sure if it's a fair assumption that users always (or at least most of the time) want to use JNI, but I currently see no other way to declare that other than to create your own WorkletContext (which is a bit cumbersome and users probably wont figure this out otherwise)
=> fix: create jni::ThreadScope on Android

cpp/JsiWorklet.h, cpp/JsiWorkletApi.cpp, cpp/JsiWorkletApi.h, cpp/JsiWorkletContext.cpp, cpp/JsiWorkletContext.h, cpp/decorators/JsiJsDecorator.h, cpp/wrappers/JsiWrapper.h, example/ios/Podfile.lock, src/decorators.ts, src/types.ts
* Applies all default decorators in `JsiWorkletContext` constructor
* Adds `Worklets.defaultContext`
* Moves `IWorkletsApi.addDecorator` to `IWorkletContext::addDecorator`
=> feat: Auto-decorate in `JsiWorkletContext` constructor

cpp/JsiWorkletContext.h, cpp/base/JsiHostObject.cpp, cpp/base/JsiHostObject.h
Hostfunctions in the HostObject can be created on multiple runtimes - this is something we need to handle in the HostObject.
This commit adds runtime as cache key as well as name.
=> fix: cache hostfunctions on both runtime and cache

cpp/wrappers/WKTJsiObjectWrapper.h
Previously host objects where returned as proxied objects when unwrapping. This is not what we want and this has now been fixed.
=> fix: hostobjects are not proxied

android/build.gradle
headers should be included like `<react-native-worklets/Header.h>`
=> fix: android headers directory

package.json, yarn.lock
Previously `string-hash-64` was added to `devDependencies`, which is only part of the RN Worklets project. For it to be also part of the user's app, we need to add it to `dependencies` here as we need `string-hash-64` to run on Metro build.
When I tried to run my app previously, metro complained about not finding `string-hash-64`. After adding it to dependencies it works - but I think without tree shaking this would make it into the end user's bundle, right? So not sure if this is the optimal solution
=> fix: add `string-hash-64` to `dependencies`

cpp/WKTJsRuntimeFactory.h, example/ios/Podfile, example/yarn.lock
When Hermes is disabled, example app is failing to build on iOS  in `cpp/WKTJsRuntimeFactory.h` line 15 with the following error: `/react-native-worklets-core/cpp/WKTJsRuntimeFactory.h:15:10 'jsc/JSCRuntime.h' file not found.`.
Note that this same issue was resolved in react-native-vision-camera. Issue: https://github.com/mrousavy/react-native-vision-camera/issues/1450. PR: https://github.com/mrousavy/react-native-vision-camera/pull/1456.
Solves: #115
=> fix: Use correct jsc lib import when hermes is disabled

cpp/WKTJsiWorklet.h, example/Tests/utils.ts, example/Tests/worklet-tests.ts, src/plugin/__tests__/__snapshots__/index.spec.js.snap, src/plugin/__tests__/index.spec.js, src/plugin/index.js
In the latest version of Reanimated, they renamed `_closure` to `__closure`. cc @tomekzaw
- https://github.com/software-mansion/react-native-reanimated/pull/4803
- https://github.com/mrousavy/react-native-vision-camera/issues/1767
=> fix: Rename `_closure` to `__closure` to fix REA compatibility

cpp/WKTJsiWorklet.h
Since location might be optional in reanimated 3.5.4 in release mode, we also made it optional here.
Fixes #127
=> Made the location prop optional

docs/USAGE.md, example/ios/Podfile.lock, src/hooks/useRunInJS.ts, src/hooks/useWorklet.ts
Creates `useRunInJS`, and adds another parameter to `useWorklet` making it a breaking change.
=> feat: Create `useRunInJS` hook

cpp/WKTJsiWorkletContext.cpp
Uses `ThreadScope::WithClassLoader` instead of just a normal `ThreadScope` so that we also have access to the custom JNI classes that might have been created by the application.
The normal ThreadScope just has access to everything that has been loaded by the System before.
Fixes https://github.com/mrousavy/react-native-vision-camera/issues/1791
=> fix: Use `ThreadScope::WithClassLoader` to access custom JNI fields

src/plugin/index.js
Adds two new typed array types to the Worklet Runtimes: [`BigInt64Array`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt64Array) and [`BigUint64Array`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigUint64Array), which are probably only supported through Hermes or JS polyfills.
With this change, the plugin also allows you to use those big-int arrays in your Worklets, assuming they are natively supported in the JS Runtime you are using (Hermes).
Needed by https://github.com/mrousavy/react-native-fast-tflite/pull/49
=> feat: Add `BigInt64Array` support

cpp/WKTJsiWorklet.h
Extracted the lambda function used in the std::all_of call into a separate named function.
Closes #144
=> fix: refactor whitespace check in createWorklet function

src/index.ts
Fixed missing export for the `useRunInJS` hook that was added in https://github.com/margelo/react-native-worklets-core/pull/139
=> fix: added missing export of useRunInJS

cpp/wrappers/WKTJsiArrayWrapper.h, example/Tests/wrapper-tests.ts
This adds a new function to the `JsiArrayWrapper` Proxy implementation that proxies JS arrays:
`shift()` following the method in Javascript it removes the first element of the array in place and returns this element.
=> feat: Add `shift` function to `JsiArrayWrapper`

cpp/WKTJsiWorklet.h, cpp/WKTJsiWorkletApi.cpp, cpp/WKTJsiWorkletApi.h, cpp/WKTJsiWorkletContext.cpp, cpp/WKTJsiWorkletContext.h, cpp/base/WKTJsiHostObject.cpp, cpp/base/WKTJsiHostObject.h, cpp/base/WKTRuntimeAwareCache.cpp, cpp/base/WKTRuntimeAwareCache.h, cpp/base/WKTRuntimeLifecycleMonitor.cpp, cpp/base/WKTRuntimeLifecycleMonitor.h, cpp/sharedvalues/WKTJsiSharedValue.h, example/ios/Podfile
To avoid keeping references to shared_ptrs that are never released, we need to make sure they are destructed on the same runtime.
This is solved by using the RuntimeAwareCache model as in Skia to make sure these key objects are only released together with the runtime they belong in.
More information can be found in the comments of the WKTRuntimeAwareCache.h file.
WKTJsiWorklet.h:
Removed the runtime teardown code from the WorkletInvoker's destructor. This is now taken care of by using the RuntimeAwareCache
WKTJsiWorkletApi.h:
Removed the passing of the default WorkletContext when creating new JsiSharedValues - the thing we want is the runtime and we can get it ourselves inside the shared value ctor.
WKTJsiWorkletContext.cpp:
Added setting the main JS Runtime on the RuntimeAwareCache so …
=> Fix/154: Better control over memory deallocation

src/hooks/useRunInJS.ts
The current type of `useRunInJS` doesn't allow any argument.
`[]` to `any[]` allows arguments in arbitrary length.
=> fix(types): fix `useRunInJS` type not allowing functions to have args

cpp/wrappers/WKTJsiArrayWrapper.h, cpp/wrappers/WKTJsiObjectWrapper.h, cpp/wrappers/WKTJsiWrapper.cpp, cpp/wrappers/WKTJsiWrapper.h
Adds locks to array and object wrappers to make multi-threaded access (read or write operations, e.g. `push()` and `pop()`)  safe.
Uses a `recursive_mutex`, might have a small performance impact.
=> feat: Lock Array and Object wrappers for safe multithreading

cpp/WKTJsiWorkletContext.cpp, cpp/base/WKTRuntimeAwareCache.cpp, cpp/base/WKTRuntimeAwareCache.h
Fixes #166 
This PR changes `RuntimeAwareCache` to also treat the main JS Runtime like any other Runtime. Before, it could happen that the main JS Runtime was refreshed and destroyed, and it's cache (`_primaryCache`) went stale. 
Now we could also explicitly delete the `_primaryCache` when the main JS runtime gets deleted somehow, but I feel like that's almost going to be the identical code to the secondary runtime part then so might make more sense to just have one path that works for all runtimes.
Cache lookups are performed like normal, listeners are attached, and cache is cleared when it is destroyed.
---
@chrfalch I am not sure if I understood your code properly since you explicitly added comments there explaining why it was treated differently from other runtimes, but I haven't …
=> fix: Fix reload crash by also listening to Main JS Runtime in `RuntimeAwareCache`

cpp/WKTJsiWorkletApi.h, cpp/WKTJsiWorkletContext.h, cpp/base/WKTJsiHostObject.cpp, docs/USAGE.md, docs/WORKLETS.md, example/Tests/sharedvalue-tests.ts, example/Tests/worklet-context-tests.ts, example/Tests/worklet-tests.ts, example/ios/Podfile.lock, example/package.json, example/yarn.lock, src/hooks/useRunInJS.ts, src/hooks/useWorklet.ts, src/types.ts
Simplifies the API of RN Worklets Core.
1. `Worklets.createRunInContextFn(func, context)` has been renamed to `context.prepareRunAsync(func)`
1. `context.runAsync(func)` has been added for convenience
2.`Worklets.createRunInJsFn(func)` has been renamed to `Worklets.prepareRunOnJS(func)`
1. `Worklets.runOnJS(func)` has been added for convenience 
Since `runAsync` is now bound to a Worklet context, to run something on the default context you would now do:
```ts
Worklets.defaultContext.runAsync(() => {
'worklet'
console.log("hi!")
})
```
This new API has two benefits:
1. It is better to read and better organized, since those methods are specific to the contexts you create. This is aligned with how native Threads work as well.
2. It is less likely to make mistakes:
1. Forgetting the `context` …
=> feat: Simplify API (`createRunInContextFn` -> `context.runAsync`)

cpp/WKTJsiWorkletApi.h, example/Tests/worklet-tests.ts, src/types.ts
Adds a new API: `Worklets.getCurrentThreadId()`
This API is useful for checking the C++ Thread ID, as that might differ between runs on Worklets if they use a modern Dispatch Queue (iOS; DispatchQueue, Android; Executor).
getCurrentThreadId() can be used to identify thread local cache, especially in graphics environments like OpenGL or Metal (Skia).
It can also be used for debugging.
=> feat: Add `Worklets.getCurrentThreadId()`

cpp/WKTJsiWorkletApi.h, src/types.ts
Instead of just silently removing `createRunInJsFn` and `createRunInContextFn`, I added those methods back but they just throw an error about the deprecation notice instead.
=> feat: Throw errors when trying to use deprecated APIs

cpp/WKTJsiWorkletApi.h, example/Tests/worklet-tests.ts, src/types.ts
This PR changes the implementation of `Worklets.getCurrentThreadId()` to not use [`std::this_thread::get_id()`](https://en.cppreference.com/w/cpp/thread/get_id), but instead just manually count IDs using a `thread_local` variable per Thread.
This also means that thread IDs are now numbers (int) instead of strings (hex).
The problem with `this_thread::get_id()` was that after a Thread has been terminated and a new thread has started, it might have the same `thread::id` as the one that was terminated, but the `thread_local` storage of that Thread has been wiped.
Skia uses `thread_local` storage, and the whole reason for that API is to find out which Thread's `thread_local` storage we are on, so the alternative is much more senseful here.
=> fix: Use `thread_local` storage to increment `getCurrentThreadId()`

cpp/wrappers/WKTJsiObjectWrapper.h
To avoid someone modifying the object wrapper from one thread while we're enumerating it we need to create a lock on the object.
=> fix: Add lock when building the property names array in JsiObjectWrapper

cpp/WKTJsiWorkletContext.cpp, cpp/wrappers/WKTJsiObjectWrapper.h
While trying to get this library working in an environment where we are unable to use hermes for 𝓇ℯ𝒶𝓈ℴ𝓃𝓈, I encountered two issues which this PR fixes.
1. NativeState is unimplemented in the react-native JSC shim before react-native 0.74.x.
2. ~~When hostFunctions are called, JSC attempts to provide globalThis as the 'this' context causing crashes (hermes provides `undefined`).~~
Should hopefully resolve https://github.com/margelo/react-native-worklets-core/issues/137
As far as I can tell, the entire test suite passes in iOS. It seems like it's also passing in android but I am unable to get consistent results.
=> fix(jsc): prevent crashes when using jsc runtime

cpp/wrappers/WKTJsiObjectWrapper.h, example/Tests/sharedvalue-tests.ts
Setting a property with different types used to fail:
```js
const sharedValue = Worklets.createSharedValue({ a: { b: 200 } });
sharedValue.value.a = undefined; // <- This failed
```
This fixes this issue.
=> fix: Added support for changing type when setting prop

cpp/wrappers/WKTJsiObjectWrapper.h
JsiObjectWrapper: When setting value in setObjectValue we forgot to lock and this might give us the dreaded getPropertyNames error?
All methods that updates or changes the _properties variable MUST use a lock.
=> fix: Added missing lock

example/Tests/worklet-tests.ts, example/src/App.tsx, src/hooks/useWorklet.ts, src/index.ts, src/worklet.ts
Adds the `worklet(...)` and `isWorklet(..)` functions:
```ts
const func = worklet(() => {
'worklet'
return "hello!"
})
context.runAsync(func)
```
This will do some runtime checking to ensure the given function is a worklet (uses `__initData`, `__closure` and `__workletHash`) and throws with some useful debugging information if it isn't. 
I will use this in VisionCamera's `useFrameProcessor` function to make sure people pass in worklets (funcs with `'worklet'` directive) and they installed the babel plugin properly. Otherwise the error is a bit cryptic, with this it's more clear what went wrong:
```diff
- ERROR  Error: The given function ("") is not a Worklet!
- - Make sure react-native-worklets-core is installed properly! 
- - Make sure to add the react-native-worklets-core babel plugin …
```
=> Add `worklet()` func that throws if value is not a worklet

cpp/wrappers/WKTJsiObjectWrapper.h, example/Tests/sharedvalue-tests.ts
Fixing bug preventing fields on a shared value object from being reassigned. `map::emplace` does not allow overwriting the value for a key that already exists.
Attempting to fix an issue I opened a couple hours ago: https://github.com/margelo/react-native-worklets-core/issues/182
=> fix: Allowing fields on a shared value object to be reassigned

example/src/App.tsx, src/NativeWorklets.ts, src/hooks/useRunOnJS.ts, src/hooks/useSharedValue.ts, src/hooks/useWorklet.ts, src/index.ts, src/types.ts, src/worklet.ts
- Improves typings for `worklet(...)` and `isWorklet(...)`
- Always export `Worklets` instead of just declaring it in global (that will prevented the missing import error)
- Remove unused old types
=> feat: Some typing improvements (`IWorklet`/`IWorkletize<>`)

cpp/WKTJsiWorklet.h, example/ios/Podfile.lock, src/plugin/index.js, src/types.ts, src/worklet.ts
Often times this library is used next to reanimated.
In this case the worklets are transpiled by the reanimated babel plugin.
The reanimated babel plugin uses `initData.sourceMap` instead of RNWC current `initData.__sourceMap`.
This has gone unnoticed so far, cause we never checked for that property.
In this PR, which was recently merged
- https://github.com/margelo/react-native-worklets-core/pull/188
a check was introduced, that checks if the provided function is a `worklet`:
https://github.com/margelo/react-native-worklets-core/blob/c495c52df85ec627c6c4d98aa785d20590322e80/src/hooks/useWorklet.ts#L6-L9
In this function we check for the `__sourceMap` identifier, which won't be present when we run with reanimated.
The solution to this seems to be to use the same identifier name as in …
=> fix: fix recent incompatibility when using reanimated

package/example/ios/Podfile.lock, package/react-native-worklets-core.podspec
see: https://blog.cocoapods.org/CocoaPods-1.5.0/
fixes this error specifically: https://github.com/margelo/react-native-worklets-core/issues/209
there is no real downside to enabling this flag, so should be fine
=> fix(ios): #209 build enable stricter header search paths

.github/workflows/build-ios.yml, example/android/gradle.properties, example/ios/Podfile.lock, example/package.json, react-native-worklets-core.podspec
RNWC already has a code path for new arch on iOS and on android its already a Turbo Module package, so thats all fine.
For iOS we had to fix the podspec though as otherwise you would get build errors ([see here for reference](https://github.com/facebook/react-native/blob/e0be2efe4e80edf99f96a2ae6a25856f6df5e0ca/packages/react-native/scripts/cocoapods/new_architecture.rb#L71))
based on this PR which should be merged first:
- https://github.com/margelo/react-native-worklets-core/pull/224
=> fix(ios): fix install problems on new arch

android/src/main/java/com/worklets/WorkletsCorePackage.java
On android the worklets core package name clashes with reanimated's worklets. Renaming to WorkletsCorePackage fixes the issue. If one also has vision camera installed one needs to clean the android build files there as well.
Tested changes in my currnet project that use worklets-core, vision camera and reanimated 4 with worklets.
=> fix: Fixes name clash with react-native-worklets
